CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    price_date DATE NOT NULL,
    open_price NUMERIC(18, 6),
    high_price NUMERIC(18, 6),
    low_price NUMERIC(18, 6),
    close_price NUMERIC(18, 6),
    adjusted_close NUMERIC(18, 6),
    volume BIGINT,
    source TEXT NOT NULL DEFAULT 'unknown',
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_raw_prices_ticker_date_source UNIQUE (ticker, price_date, source)
);

CREATE TABLE IF NOT EXISTS raw.assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL UNIQUE,
    asset_name TEXT,
    asset_class TEXT NOT NULL,
    sector TEXT,
    currency TEXT NOT NULL,
    country TEXT,
    benchmark_ticker TEXT
);

CREATE TABLE IF NOT EXISTS raw.portfolio_positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_name TEXT NOT NULL,
    ticker TEXT NOT NULL,
    quantity NUMERIC(18, 6) NOT NULL,
    as_of_date DATE NOT NULL,
    asset_class TEXT,
    sector TEXT,
    currency TEXT
);

