CREATE SCHEMA IF NOT EXISTS mart;

CREATE TABLE IF NOT EXISTS mart.daily_returns (
    ticker TEXT NOT NULL,
    return_date DATE NOT NULL,
    daily_return NUMERIC(18, 10) NOT NULL,
    log_return NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (ticker, return_date)
);

CREATE TABLE IF NOT EXISTS mart.portfolio_values (
    portfolio_name TEXT NOT NULL,
    value_date DATE NOT NULL,
    market_value NUMERIC(18, 6) NOT NULL,
    daily_pnl NUMERIC(18, 6) NOT NULL,
    daily_return NUMERIC(18, 10) NOT NULL,
    cumulative_return NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (portfolio_name, value_date)
);

CREATE TABLE IF NOT EXISTS mart.position_pnl (
    portfolio_name TEXT NOT NULL,
    value_date DATE NOT NULL,
    ticker TEXT NOT NULL,
    position_value NUMERIC(18, 6) NOT NULL,
    daily_pnl NUMERIC(18, 6) NOT NULL,
    contribution_to_pnl NUMERIC(18, 6) NOT NULL,
    contribution_to_return NUMERIC(18, 10) NOT NULL,
    weight NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (portfolio_name, value_date, ticker)
);

CREATE TABLE IF NOT EXISTS mart.risk_metrics (
    portfolio_name TEXT NOT NULL,
    metric_date DATE NOT NULL,
    metric_name TEXT NOT NULL,
    metric_value NUMERIC(18, 10) NOT NULL,
    lookback_days INTEGER,
    confidence_level NUMERIC(6, 4),
    PRIMARY KEY (portfolio_name, metric_date, metric_name)
);

CREATE TABLE IF NOT EXISTS mart.exposures (
    portfolio_name TEXT NOT NULL,
    exposure_date DATE NOT NULL,
    exposure_type TEXT NOT NULL,
    exposure_name TEXT NOT NULL,
    market_value NUMERIC(18, 6) NOT NULL,
    weight NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (portfolio_name, exposure_date, exposure_type, exposure_name)
);

CREATE TABLE IF NOT EXISTS mart.stress_test_results (
    portfolio_name TEXT NOT NULL,
    scenario_name TEXT NOT NULL,
    run_timestamp TIMESTAMPTZ NOT NULL,
    shocked_portfolio_value NUMERIC(18, 6) NOT NULL,
    stress_loss NUMERIC(18, 6) NOT NULL,
    stress_return NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (portfolio_name, scenario_name, run_timestamp)
);

CREATE TABLE IF NOT EXISTS mart.monte_carlo_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_name TEXT NOT NULL,
    run_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    initial_value NUMERIC(18, 6) NOT NULL,
    horizon_days INTEGER NOT NULL,
    n_simulations INTEGER NOT NULL,
    confidence_level NUMERIC(6, 4) NOT NULL,
    lookback_days INTEGER,
    random_seed INTEGER
);

CREATE TABLE IF NOT EXISTS mart.monte_carlo_results (
    run_id BIGINT NOT NULL REFERENCES mart.monte_carlo_runs(run_id),
    metric_name TEXT NOT NULL,
    metric_value NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (run_id, metric_name)
);

CREATE TABLE IF NOT EXISTS mart.monte_carlo_terminal_values (
    run_id BIGINT NOT NULL REFERENCES mart.monte_carlo_runs(run_id),
    simulation_id INTEGER NOT NULL,
    terminal_value NUMERIC(18, 6) NOT NULL,
    terminal_return NUMERIC(18, 10) NOT NULL,
    max_drawdown NUMERIC(18, 10) NOT NULL,
    PRIMARY KEY (run_id, simulation_id)
);

CREATE TABLE IF NOT EXISTS mart.data_quality_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_name TEXT NOT NULL,
    status TEXT NOT NULL,
    severity TEXT NOT NULL,
    ticker TEXT,
    check_date DATE,
    message TEXT NOT NULL,
    run_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

